default_platform(:ios)

before_all do
	cocoapods
end

platform :ios do
  lane :clean_build do
  	sh("cp", "../MovieApp/TMDB.plist.sample", "../MovieApp/TMDB.plist")
  	xcodebuild(
  		scheme: "MovieApp",
  		clean: true,
  		build: true,
  		xcargs: "CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS= CODE_SIGNING_ALLOWED=NO"
  	)
  end
end
